const actionTypes = {
    GET_HOME: 'GET_HOME',
    LOADING: 'LOADING',
    SET_CUR_SONG_DATA: 'SET_CUR_SONG_DATA',
    SET_CUR_ALBUM_ID: 'SET_CUR_ALBUM_ID',
    SET_RECENT: 'SET_RECENT',
    CURRENT_WIDTH: 'CURRENT_WIDTH',

    //music
    SET_CUR_SONG_ID: 'SET_CUR_SONG_ID',
    PLAY: "PLAY",
    SET_ALBUM: 'SET_ALBUM',
    PLAY_LIST: 'PLAY_LIST',
    SEARCH: 'SEARCH',
    ZERO_SCROLLTOP: 'ZERO_SCROLLTOP',

}

export default actionTypes